package com.dartbarrel.plugin.settings

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.components.PersistentStateComponent
import com.intellij.openapi.components.State
import com.intellij.openapi.components.Storage
import com.intellij.util.xmlb.XmlSerializerUtil

@State(
    name = "DartBarrelSettings",
    storages = [Storage("DartBarrelSettings.xml")]
)
class DartBarrelSettings : PersistentStateComponent<DartBarrelSettings> {

    var barrelFileName: String = "{folder_name}.dart"
    var includeHeader: Boolean = false
    var headerComment: String = "// Generated by Dart Barrel Manager"
    var autoGenerate: Boolean = false
    var excludePatterns: MutableList<String> = mutableListOf(
        ".*\\.g\\.dart",
        ".*\\.freezed\\.dart",
        ".*\\.gr\\.dart",
        ".*\\.config\\.dart",
        ".*\\.part\\.dart",
    )
    var sortExports: Boolean = true

    override fun getState(): DartBarrelSettings = this

    override fun loadState(state: DartBarrelSettings) {
        XmlSerializerUtil.copyBean(state, this)
    }

    companion object {
        fun getInstance(): DartBarrelSettings {
            return ApplicationManager.getApplication()
                .getService(DartBarrelSettings::class.java)
        }
    }
}